---
title: "Trabalho Final CDA MDT-01 - Flashdashboard"
author: "Alexandre e Jorge"
date: "22/06/2020"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
---

```{r global, include=FALSE}

library(tidyverse)
library(flexdashboard)
library(lubridate)
library(viridis)
library(hrbrthemes)

knitr::opts_chunk$set(cache=F)


# Leitura de Arquivos de Viagens

DiretorioBase="/cloud/project/Data/Viagem/"
ArquivosNomes<-list.files(DiretorioBase, pattern="*.csv")


df_Pagamento <- read_csv2(paste0(DiretorioBase,ArquivosNomes[1]), locale = locale(encoding = "latin1"))
df_Passagem <- read_csv2(paste0(DiretorioBase,ArquivosNomes[2]), locale = locale(encoding = "latin1"))
df_Trecho <- read_csv2(paste0(DiretorioBase,ArquivosNomes[3]), locale = locale(encoding = "latin1"))
df_Viagem <- read_csv2(paste0(DiretorioBase,ArquivosNomes[4]), locale = locale(encoding = "latin1"))



# Agrupa e soma valores gastos por dia e Órgao solicitante para as Viagens Realizadas

df_valor_org_dia <- df_Viagem %>% 
                              filter(Situacao=="Realizada") %>%
                              group_by(Nome_orgao_solicitante,Periodo_Data_de_inicio) %>%
                              summarize(ValorTotalDiarias=sum(Valor_diarias),
                                        ValorTotalOutros=sum(Valor_outros_gastos),
                                        ValorTotalPassagens=sum(Valor_passagens),
                                        Qtd=n())
df_valor_org_dia$Periodo_Data_de_inicio <- as.Date(dmy(df_valor_org_dia$Periodo_Data_de_inicio))


# Agrupa e soma valores gastos em Diárias, Passagens e Outras Despesas por Órgao solicitante para as Viagens Realizadas

df_valor_org_solicitante <- df_Viagem %>% 
                              filter(Situacao=="Realizada") %>%
                              group_by(Nome_orgao_solicitante) %>%
                              summarize(ValorTotalDiarias=sum(Valor_diarias),
                                        ValorMedioDiarias=mean(Valor_diarias),
                                        ValorMaxDiarias=max(Valor_diarias),
                                        ValorTotalOutros=sum(Valor_outros_gastos),
                                        ValorMedioOutros=mean(Valor_outros_gastos),
                                        ValorMaxOutros=max(Valor_outros_gastos),
                                        ValorTotalPassagens=sum(Valor_passagens),
                                        ValorMedioPassagens=mean(Valor_passagens),
                                        ValorMaxPassagens=max(Valor_passagens),
                                        Qtd=n())

# Efetua a separação das Viagens Urgentes

df_valor_org_solic_urgente <- df_Viagem %>% 
                              filter(Situacao=="Realizada") %>%
                              group_by(Nome_Orgao_Superior,Viagem_Urgente) %>%
                              summarize(ValorTotalDiarias=sum(Valor_diarias),
                                        ValorMedioDiarias=mean(Valor_diarias),
                                        ValorMaxDiarias=max(Valor_diarias),
                                        ValorTotalOutros=sum(Valor_outros_gastos),
                                        ValorMedioOutros=mean(Valor_outros_gastos),
                                        ValorMaxOutros=max(Valor_outros_gastos),
                                        ValorTotalPassagens=sum(Valor_passagens),
                                        ValorMedioPassagens=mean(Valor_passagens),
                                        ValorMaxPassagens=max(Valor_passagens),
                                        Qtd=n())


dia_min <- df_valor_org_dia$Periodo_Data_de_inicio %>% min
dia_max <- df_valor_org_dia$Periodo_Data_de_inicio %>% max


passagens_total <- df_valor_org_dia$ValorTotalPassagens %>% sum(na.rm=T)
diarias_total <- df_valor_org_dia$ValorTotalDiarias %>% sum(na.rm=T)
outros_total <- df_valor_org_dia$ValorTotalOutros %>% sum(na.rm=T)


```

# Aba Principal - Viagem

## Row 1

### Passagens de `r dia_min` a `r dia_max` (mil R$)

<!-- ícones em: https://fontawesome.com/v4.7.0/icons/ -->

```{r,message=F}
valueBox(round(passagens_total/10^3,1), icon = "fa-bomb")
```

### Diárias de `r dia_min` a `r dia_max` (mil R$)

```{r,message=F}
valueBox(round(diarias_total/10^3,1), icon = "fa-exclamation-circle",
         color="purple")
```

### Outras de `r dia_min` a `r dia_max` (mil R$)

<!-- ícones em: https://fontawesome.com/v4.7.0/icons/ -->

```{r,message=F}
valueBox(round(outros_total/10^3,1), icon = "fa-bomb",
         color="red")
```





## Row 2

### 5 Maiores Despesas de Passagens no Ano

```{r}

 df_valor_org_solicitante %>%  arrange(desc(ValorTotalPassagens)) %>% head(5)  %>%
    mutate(Nome_orgao_solicitante = fct_reorder(Nome_orgao_solicitante, (ValorTotalPassagens))) %>%
    ggplot(aes(fill=Qtd, y=ValorTotalPassagens/1000, x=Nome_orgao_solicitante)) + 
    geom_bar(position="stack", stat="identity") +
    labs(y="" , x = "")  +  
    coord_flip() 

```

### 5 Maiores Despesas de Diárias no Ano

```{r,message=F}

    df_valor_org_solicitante %>%  arrange(desc(ValorTotalDiarias)) %>% head(5)  %>%
    mutate(Nome_orgao_solicitante = fct_reorder(Nome_orgao_solicitante, (ValorTotalDiarias))) %>%
    ggplot(aes(fill=Qtd, y=ValorTotalDiarias/1000, x=Nome_orgao_solicitante)) + 
    geom_bar(position="stack", stat="identity") +
    labs(y="" , x = "")  +  
    coord_flip() 

```

### 5 Maiores Outras Despesas de Viagem no Ano

```{r}


   df_valor_org_solicitante %>%  arrange(desc(ValorTotalOutros)) %>% head(5)  %>%
    mutate(Nome_orgao_solicitante = fct_reorder(Nome_orgao_solicitante, (ValorTotalOutros))) %>%
    ggplot(aes(fill=Qtd, y=ValorTotalOutros/1000, x=Nome_orgao_solicitante)) + 
    geom_bar(position="stack", stat="identity") +
    labs(y="" , x = "")  +  
    coord_flip() 

```



## Row 3

### Relação de Viagens Urgentes x Normais por Ministério

```{r}


    df_valor_org_solic_urgente %>%  mutate(Total=(ValorTotalPassagens+ValorTotalOutros+ValorTotalDiarias)) %>%
    ggplot(aes(fill=Viagem_Urgente, y=(Total)/1000, x=reorder(Nome_Orgao_Superior,Total))) + 
    geom_bar(position="dodge", stat="identity") +
    labs(y="" , x = "")  +  
    coord_flip() 




```


### Distribuição das Despesas por Ministério

```{r,message=F}


df_Viagem %>% 
  filter(Situacao=="Realizada") %>%
  ggplot( aes(x=Nome_Orgao_Superior, y=Valor_diarias+Valor_passagens+Valor_outros_gastos, fill=Nome_Orgao_Superior)) +
    geom_boxplot() +
    scale_fill_viridis(discrete = TRUE, alpha=0.6) +
    geom_jitter(color="black", size=0.01, alpha=0.01) +
    theme_ipsum() +
    theme(
      legend.position="none",
      plot.title = element_text(size=10)
    ) +
    ggtitle("") +
   xlab('') +
   ylab('') +
    coord_flip()





```


